version: 2.1

orbs:
  cimg: circleci/cimg@0.3.4

jobs:
  automated-wf:
    docker:
      - image: cimg/android:2023.11.1
    steps:
      - checkout
      - run: cmod +x androidFeed.sh
      - run: ./androidFeed.sh
workflows:
  main-wf:
    jobs:
      - cimg/build-and-deploy:
          name: "Staging"
          docker-namespace: ccitest
          docker-repository: android
          publish-branch: test
          filters:
            branches:
              ignore:
                - main
          context: cimg-publishing
      - cimg/build-and-deploy:
          name: "Deploy"
          docker-repository: android
          filters:
            branches:
              only:
                - main
          context: cimg-publishing
  check-feed:
    jobs:
      - automated-wf
