version: 2.1

orbs:
  cimg: circleci/cimg@0.6.5
parameters:
  cron:
    type: boolean
    default: false

workflows:
  main-wf:
    when:
      not: << pipeline.parameters.cron >>
    jobs:
      - cimg/build-and-deploy:
          name: "Test"
          resource-class: medium.gen2
          docker-namespace: ccitest
          docker-repository: android
          filters:
            branches:
              ignore:
                - main
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
      - cimg/build-and-deploy:
          name: "Deploy"
          resource-class: medium.gen2
          docker-repository: android
          filters:
            branches:
              only:
                - main
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cimg-docker-image-building
            - cimg-docker-image-publishing
  check-feed:
    when: << pipeline.parameters.cron >>
    jobs:
      - cimg/update:
          resource-class: small.gen2
          update-script: androidFeed.sh
          image: cimg/android
          tag: "2026.03.1"
          context:
            - slack-notification-access-token
            - slack-cimg-notifications
            - cpe-image-bot-github-creds
