version: 2.1

orbs:
  sonar: hubci/sonar@1.0

workflows:
  main:
    jobs:
      - build:
          context: cimg-publishing

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
          echo 'export DOCKER_PASS=$DOCKER_TOKEN' >> $BASH_ENV
      - sonar/install:
          version: 0.14.1
      - run: sonar tags delete --dry-run cimg/android 25.0,25.0.0,28.0.0,26.0,26.0.0,27.0.0,29.0.0,27.0,28.0,29.0,30.0,31.0
