version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0

workflows:
  main:
    jobs:
      - update-readme:
          context: cimg-publishing

jobs:
  update-readme:
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout
      - sonar/install:
          version: "0.15.0"
      - sonar/update-readme:
          image: cimg/android
