version: 2.1

orbs:
  cimg: circleci/cimg@0.6.4

parameters:
  cron:
    type: boolean
    default: false

workflows:
  main-wf:
    when:
      not: << pipeline.parameters.cron >>
    jobs:
      - cimg/build-and-deploy:
          name: "Test"
          docker-namespace: ccitest
          docker-repository: android
          filters:
            branches:
              ignore:
                - main
          context: cimg-docker-image-building
      - cimg/build-and-deploy:
          name: "Deploy"
          docker-repository: android
          filters:
            branches:
              only:
                - main
          context:
            - cimg-docker-image-building
            - cimg-docker-image-publishing
  check-feed:
    when: << pipeline.parameters.cron >>
    jobs:
      - cimg/update:
          update-script: androidFeed.sh
          image: cimg/android
          tag: "2023.11.1"
          context:
            - cpe-image-bot-github-creds
